# Generated by Django 6.0.5 on 2026-05-07 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo_dias', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='CicloOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.ciclo')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.responsable')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipoTurno', models.CharField(choices=[('normal', 'Normal'), ('cobertura', 'Cobertura'), ('intercambio', 'Intercambio')], default='normal', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.ciclo')),
                ('responsable_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_original', to='turnos.responsable')),
                ('responsable_reemplazo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable_reemplazo', to='turnos.responsable')),
            ],
        ),
    ]
